### ISSUE TITLE
Error creating VM instance

### ISSUE THREAD

**Issue by ryanwalexander** [dadatuputi/bitwarden_gcloud#1]
Hi there,

Really appreciate your work, however I'm getting an error from google cloud when I try to spin up the VM with the commands you provided.  It's probably something basic since I'm relatively new to this.

`gcloud compute instances create bitwarden \
    --machine-type f1-micro \
    --zone us-central1-a \
    --image-project cos-cloud \
    --image-family cos-stable \
    --boot-disk-size=30GB \
    --tags http-server,https-server \
    --scopes compute-ro`

returns the following:

`ERROR: (gcloud.compute.instances.create) The project property is set to the empty string, which is invalid.
To set your project, run:
  $ gcloud config set project PROJECT_ID
or to unset it, run:
  $ gcloud config unset project`

**Comment by ryanwalexander** [comment]
Turns out I needed to set the project with the command they suggested first... Issue resolved.

**Comment by ryanwalexander** [comment]
Now I'm stuck on https://bradford.la/2020/self-host-bitwarden-on-google-cloud/#env-file .  Not sure what to do with the file once I edit it or why it didn't appear to clone.

I really appreciate your steps but it looks to be a bit ahead of my current skillset.  Perhaps I'll come back when my skills are more upgraded.

**Comment by dadatuputi** [comment]
@ryanwalexander Yeah that part is a bit sparse on documentation. The repo comes with .env.template, so rename it to .env and add the values. There is some documentation in it that should guide you along. Did you do all that?

**Comment by ryanwalexander** [comment]
It actually looks like it didn't clone over, and I'm not sure how to get at the file anymore. 

`~/bitwarden_gcloud $ dir
LICENSE  README.md  bitwarden  caddy  countryblock  ddns  docker-compose.yml  fail2ban  utilities`

Am I supposed to upload it over SSH or is there another way to get it there?

**Comment by dadatuputi** [comment]
Try `ls -al` - any file preceded by a dot is a hidden file and won't show up unless you tell ls/dir to show hidden files

**Comment by ryanwalexander** [comment]
That's very helpful.  Should have a chance to give it a try later today.  Thank you.
