### ISSUE TITLE
Tags do not allow HTTP/HTTPS automatically

### ISSUE THREAD

**Issue by carceneaux** [dadatuputi/bitwarden_gcloud#14]
First off, thanks for this AWESOME project! 🚀 

I used the provided Google Cloud console command to create my VM instance and the `tags` mentioned in your documentation no longer open the firewall for those respective ports incoming.

```
gcloud compute instances create bitwarden \
    --machine-type f1-micro \
    --zone us-central1-a \
    --image-project cos-cloud \
    --image-family cos-stable \
    --boot-disk-size=30GB \
    --tags http-server,https-server \
    --scopes compute-rw
```

To resolve this...I had to edit my VM instance and check the boxes shown below.

![image](https://user-images.githubusercontent.com/17179966/111994159-d1ff8c00-8aed-11eb-9aed-04cf5dfb0176.png)

**Comment by dadatuputi** [comment]
Thanks for the feedback. I was under the impression that adding the tags was the same thing, but it appears that was never the case, or it changed recently. The PR https://github.com/dadatuputi/bitwarden_gcloud/pull/12 adds instructions that should also take care of this. I will investigate and then update the instructions to clarify the best path.
