### ISSUE TITLE
VM freezes after auto updated

### ISSUE THREAD

**Issue by jeffery9876** [dadatuputi/bitwarden_gcloud#15]
Hi, thank you for setting up the project. Today I found the GCP VM instance freezes - not able to open any webpage, not able to SSH into the machine.

From the console I can see there is an error right after reboot and update. Then the CPU and disk usage has been very high for the rest of the day. I tried to reboot the instance from the console, but it didn’t help. The CPU usage was still very high.  

Does anyone else has this issue today or before? I managed to fix the issue by turned it off for an hour and restart all docker containers.

---------
Attached the GCP log and CPU monitor graph. 

    {
      "insertId": "10",
      "jsonPayload": {
        "bootCounter": "3",
        "@type": "type.googleapis.com/cloud_integrity.IntegrityEvent",
        "lateBootReportEvent": {
          "policyEvaluationPassed": false,
          "actualMeasurements": [
            {
              "pcrNum": "PCR_0",
              "value": "UcMj3gwMaU9GAc3QK+tY/xNin3Q=",
              "hashAlgo": "SHA1"
            },
            {
              "pcrNum": "PCR_4",
              "value": "joEJJy/jTEhTw0+EsfsL0vjiwso=",
              "hashAlgo": "SHA1"
            },
            {
              "pcrNum": "PCR_5",
              "value": "vmeIcR8mGESZIKZKAgVNYYY+QFw=",
              "hashAlgo": "SHA1"
            },
            {
              "value": "oiHFqlAmHCH6ZlnJprPlJFd/yxw=",
              "pcrNum": "PCR_7",
              "hashAlgo": "SHA1"
            },
            {
              "pcrNum": "PCR_8",
              "hashAlgo": "SHA1",
              "value": "aeZdy3+ccTB0TEk5N2+u3t+cjdE="
            },
            {
              "value": "mqgxkyUdzWlZb5x3pHRUthvQybo=",
              "hashAlgo": "SHA1",
              "pcrNum": "PCR_9"
            }
          ],
          "policyMeasurements": [
            {
              "hashAlgo": "SHA1",
              "pcrNum": "PCR_0",
              "value": "UcMj3gwMaU9GAc3QK+tY/xNin3Q="
            },
            {
              "pcrNum": "PCR_4",
              "value": "joEJJy/jTEhTw0+EsfsL0vjiwso=",
              "hashAlgo": "SHA1"
            },
            {
              "pcrNum": "PCR_7",
              "hashAlgo": "SHA1",
              "value": "oiHFqlAmHCH6ZlnJprPlJFd/yxw="
            },
            {
              "hashAlgo": "SHA1",
              "value": "+SMuzZi6Mon8TNGawCYlUolcPH8=",
              "pcrNum": "PCR_8"
            },
            {
              "pcrNum": "PCR_9",
              "hashAlgo": "SHA1",
              "value": "qn51Aa8ACMGXHClTIzLpVoN6aVA="
            }
          ]
        }
      },
      "resource": {
        "type": "gce_instance",
        "labels": {

        }
      },
      "timestamp": "2021-04-06T06:00:13.402710160Z",
      "severity": "ERROR",
      "logName": "projects/jl-services/logs/compute.googleapis.com%2Fshielded_vm_integrity",
      "receiveTimestamp": "2021-04-06T06:00:15.411251379Z"
    }

![IMG_0002](https://user-images.githubusercontent.com/1209045/113785200-9213e800-972e-11eb-93bd-f488dffdaf5e.PNG)

**Comment by carceneaux** [comment]
I encountered the same issue this morning as well. From what I gathered, Docker required more CPU/RAM than the f1-micro machine type had available which, in my case, left nothing working and me unable to SSH into the VM so I was completely blind. Just like the OP, I also tried resetting/power cycling the VM instance a couple times but that didn't resolve the issue.

I was able to get around this by temporarily changing the machine type of the VM Instance from `f1-micro` to `g1-small`. This allowed the VM to boot properly and perform what it needed to do. After that, BitWarden was working properly so I powered off the VM instance and reverted back to the free tier machine type: `f1-micro`.

**Comment by carceneaux** [comment]
Here's the difference in specs between `f1-micro` and `g1-small`:

![image](https://user-images.githubusercontent.com/17179966/113802028-fa130000-9727-11eb-9d02-eea6781187e6.png)

**Comment by carceneaux** [comment]
Turns out the this issue was one of my own making. I used two more containers for backup purposes. One produced a file-level backup of the BW db and another copied backups and other files to a remote S3 bucket.

Even though `ddclient` is disabled in my environment, these two containers add sufficient CPU/RAM overhead that it caused Docker to have insufficient resources on boot. Yesterday, I disabled my additional containers as a test and this mornings reboot worked without a problem.

While this is great that I figured this out, it kind of sucks as I have to rethink my backup strategy (which has been working great for a couple weeks now until this).

**Comment by dadatuputi** [comment]
Thanks for documenting all this and finding the root cause. It sounds like there's not a lot of head room for additional containers/features. I'm going to experiment in the coming weeks with a backup script but limit it to e-mail. It sounds like what you were doing @carceneaux wasn't very resource intensive, but maybe the overhead of two additional containers was too much. 

@jeffery9876 - are you running anything than the vanilla config from the project? Or have you added containers as well? Your CPU utilization is way higher than anything I've ever seen with mine.

**Comment by jeffery9876** [comment]
I installed the Bitwarden only 5 days ago on last weekend. It's with the vanilla config from the project and no new container. But I changed the system docker config for portainer monitoring:

    # restarted the docker daemon and opened port 2375
    https://gist.github.com/kekru/974e40bb1cd4b947a53cca5ba4b0bbe5

My VM instance runs fine after the reported issue. But my docker modifications has been reset to original. I suspect there was an image update ( and overwrites my changes ). 

Not sure what was wrong, but I don't want to change it anymore. let's see if the same issue would happen again.

**Comment by mdsupport** [comment]
> I'm going to experiment in the coming weeks with a backup script but limit it to e-mail

Can the backup script not just save tar to the google drive of the owner of the vm as discussed [here](https://towardsdatascience.com/uploading-files-to-google-drive-directly-from-the-terminal-using-curl-2b89db28bb06)?

**Comment by dadatuputi** [comment]
@mdsupport - that's an interesting solution. It's possible, but I'm worried that the resource demands for the project are going to outgrow the micro instance it is designed for. I'll see what is available in the vaultwarden container and try to build a good simple solution, and try to make it as general purpose as possible so people can do what you suggest.

**Comment by JasperE84** [comment]
As of recently I've been getting this error as well. I was running plain vanilla bitwarden_gcloud, without the backup scripts or any extra containers.

The vm would become completely unresponsive as written before. In the serial log output window in GCP, I can see the Out of Memory Killer (linux native) at work (it killed the cloudinit process). 

To remediate I have to forcefully shut down the image. Wait a while and restart. I hoped this would be a one time thing,  yet yesterday the issue occurred again. I noticed I had to reboot twice to get it running again.

Not really sure what triggers the out of memory problem. Mem usage seems fine:

```
bitwarden-us ~/bitwarden_gcloud $ free -h
              total        used        free      shared  buff/cache   available
Mem:          580Mi       224Mi        83Mi       0.0Ki       272Mi       273Mi
Swap:            0B          0B          0B

```

**Comment by JasperE84** [comment]
Ok so this happened again. I disabled the reboot at 06.00. Sometimes booting after a cos update seems to cause the issues.

I have attached a serial log and some screenshots, looking very similar to @jeffery9876 's issue.

[partial_serial_log.txt](https://github.com/dadatuputi/bitwarden_gcloud/files/6834764/partial_serial_log.txt)
<img width="1054" alt="overview" src="https://user-images.githubusercontent.com/12022716/126038723-b31f2bad-6adf-4f25-98a0-202c09e60682.png">
<img width="255" alt="logs" src="https://user-images.githubusercontent.com/12022716/126038724-c1d65df0-bf64-44ce-aa76-73bc970b0bdd.png">

The error in gcp log:
```
{
  "insertId": "38",
  "jsonPayload": {
    "@type": "type.googleapis.com/cloud_integrity.IntegrityEvent",
    "lateBootReportEvent": {
      "policyEvaluationPassed": false,
      "policyMeasurements": [
        {
          "value": "UcMj3gwMaU9GAc3QK+tY/xNin3Q=",
          "hashAlgo": "SHA1",
          "pcrNum": "PCR_0"
        },
        {
          "pcrNum": "PCR_4",
          "value": "gjbrpzKsEcmqaVGEtzW0Vm/xlT0=",
          "hashAlgo": "SHA1"
        },
        {
          "pcrNum": "PCR_7",
          "hashAlgo": "SHA1",
          "value": "oiHFqlAmHCH6ZlnJprPlJFd/yxw="
        },
        {
          "value": "i4no3XZlS3/LHqXvC4hvWqeJnAM=",
          "hashAlgo": "SHA1",
          "pcrNum": "PCR_8"
        },
        {
          "hashAlgo": "SHA1",
          "pcrNum": "PCR_9",
          "value": "BcgRGGsmMPGgbiTR+fxG6qjZMPc="
        }
      ],
      "actualMeasurements": [
        {
          "pcrNum": "PCR_0",
          "value": "UcMj3gwMaU9GAc3QK+tY/xNin3Q=",
          "hashAlgo": "SHA1"
        },
        {
          "value": "gjbrpzKsEcmqaVGEtzW0Vm/xlT0=",
          "pcrNum": "PCR_4",
          "hashAlgo": "SHA1"
        },
        {
          "value": "3xcBczPw6317U4bSO4hTl94aBdI=",
          "hashAlgo": "SHA1",
          "pcrNum": "PCR_5"
        },
        {
          "hashAlgo": "SHA1",
          "pcrNum": "PCR_7",
          "value": "oiHFqlAmHCH6ZlnJprPlJFd/yxw="
        },
        {
          "hashAlgo": "SHA1",
          "pcrNum": "PCR_8",
          "value": "LlIqlSngMVZPtwfgZvJe5m3w1jU="
        },
        {
          "value": "2oAi5VRYv6UWyvTTJ0iKgV/PT58=",
          "hashAlgo": "SHA1",
          "pcrNum": "PCR_9"
        }
      ]
    },
    "bootCounter": "38"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "zone": "us-west1-b",
      "project_id": "f1-micro-free-****",
      "instance_id": "*****"
    }
  },
  "timestamp": "2021-07-17T04:01:38.709095722Z",
  "severity": "ERROR",
  "logName": "projects/f1-micro-free-*****/logs/compute.googleapis.com%2Fshielded_vm_integrity",
  "receiveTimestamp": "2021-07-17T04:01:40.718358951Z"
}
```

**Comment by JasperE84** [comment]
Problem kept returning. Recreated VM instance and that seems to have solved it
