### ISSUE TITLE
Change from F1 to E2

### ISSUE THREAD

**Issue by jeffery9876** [dadatuputi/bitwarden_gcloud#19]
We’ve identified that you’re using an F1-micro instance that is a part of the Compute Engine Free Tier. As we improve the experience of the Free Tier, we will be introducing the E2-micro VM, which is a part of a second generation VM family. It offers additional resources for your use, specifically 0.25 vCPU (which burst to 2 vCPU periodically) and 1 GB of RAM.

What do I need to know?
The Free Tier F1-micro VM is changing to the E2-micro VM as the VM to use for free. On August 1, 2021, E2-micro Free Tier will be introduced. Follow these steps to change your machine type to E2-micro to avoid incurring charges for continuing to use F1-micro after August 31, 2021.

What do I need to do?
Starting August 1, 2021, change the machine type from F1-micro, or stop your existing F1-micro instance and begin using a E2-micro instance. VMs created with either method will automatically have the Free Tier discount applied to them. The supported regions will remain the same.

**Comment by dadatuputi** [comment]
I'll update the guide to reflect this. Thanks.

**Comment by carceneaux** [comment]
Thx for the friendly reminder! Despite two emails from Google, I had let this slip my mind.
