### ISSUE TITLE
New free tier misconfigured

### ISSUE THREAD

**Issue by borntohonk** [dadatuputi/bitwarden_gcloud#25]
Hi, the default configuration you use is not applicable for the E2 free tier.

"Google Cloud Free Tier does not include external IP addresses"

you would have to supply --no-address and configure a bunch of other stuff, to stay in line with that.

**Comment by carceneaux** [comment]
That line has been in the free tier docs for a while now. While I know it applies to a **static** external IP, I've never been charged for an **ephemeral** external IP.

An ephemeral IP just means you might be assigned after a power off/on operation.
