### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by mdsupport** [dadatuputi/bitwarden_gcloud#28]
Google takes care of automatically updating the OS. Are there any standard instructions to pull all latest updates for an old installation of this project from github? Is periodic `git pull` recommended?

**Comment by carceneaux** [comment]
As long as `watchtower` was defined in your [docker-compose.yml](https://github.com/dadatuputi/bitwarden_gcloud/blob/master/docker-compose.yml#L156), it keeps all container images up to date.

As such, there shouldn't be a need to pull updates from this project.
