### ISSUE TITLE
Want to use a new domain using Caddy

### ISSUE THREAD

**Issue by ritun-guha** [dadatuputi/bitwarden_gcloud#34]
Hello There, 

I have already configured Bitwarden using this Github repo. 

Now My client wants to use a new domain on that server for another application. 

Can you please guide me how put that domain name along with Bitwarden domain and ssl enables also. 

Reverse proxy want to use

**Comment by dadatuputi** [comment]
If your client is doing this in GCloud's free tier, I don't think it will handle many other services running. If they are using it in a different environment, I suggest you look at `caddy/Caddyfile` - you can have multiple domains defined there, so you could add another domain that then proxies it to a different container that's running. That's outside the scope of this project, so you're on your own for implementing it. Caddy has great documentation, and you would probably have to add services to the docker-config.yml. Good luck.
