### ISSUE TITLE
Can't get Rclone working

### ISSUE THREAD

**Issue by quarthio** [dadatuputi/bitwarden_gcloud#35]
From the instructions in https://github.com/dadatuputi/bitwarden_gcloud/blob/master/.env.template I try to setup Rclone backups. When running the following command:

`sudo docker exec -it bitwarden rclone config --config $BACKUP_RCLONE_CONF`

I get the following error:

`OCI runtime exec failed: exec failed: unable to start container process: exec: "rclone": executable file not found in $PATH: unknown`

Which I couldn't fix. Please help me out.

**Comment by frankyboy1604** [comment]
I have the same Problem. Maybe it is a problem in the Vaultwarden container?

**Comment by ilyadel** [comment]
Rclone is not  yet installed on bitwarden container.  you can do it by launching the command  : 
`sudo docker exec -it bitwarden ash /backup.sh rclone`
The backup will probably fail, but the script will install rclone and you can continue the configuration.

**Comment by dadatuputi** [comment]
Hey @frankyboy1604, I see your pull request. Nice work. Asking here because you laid it out, but why your 6th step? I have a working rclone config that has a name other than `remote`. Why is that necessary?

**Comment by frankyboy1604** [comment]
You are right. The problem was that I used a name like 'dropbox remote' with spaces in it. I fixed it in the backup.sh script. Now you can use remote names with spaces in it.
The 6th step ist not necessary.
