### ISSUE TITLE
toolbox not found

### ISSUE THREAD

**Issue by Larosen** [dadatuputi/bitwarden_gcloud#36]
I was able to download everything and edit the .env file and everything worked just fine until I came to the point where I should use the toolbox command. 
When I type `toolbox` it responds:
`***@cs-****-default:~/bitwarden_gcloud$ toolbox`
`-bash: toolbox: command not found`

Does anyone know how I should proceed from here?

**Comment by dadatuputi** [comment]
Hi @Larosen, are you doing this in a GCloud Container-Optimized OS? If you are sure that you are and still have that issue, can you find the binary at `/usr/bin/toolbox`

Try looking through https://cloud.google.com/container-optimized-os/docs/how-to/toolbox to see if that leads anywhere.
