### ISSUE TITLE
Add docs on using duckdns.org

### ISSUE THREAD

**Issue by casonadams** [dadatuputi/bitwarden_gcloud#39]
update .env vars

```
### GLOBAL VARIABLES ###

# The fully-qualified domain name for Bitwarden - what address do you want Bitwarden accessible?
# Do not include the protocol (http/https), that is added when needed in docker-compose.yml
# Used for caddy proxy and ddns with Cloudflare
DOMAIN=<sub-domain>.duckdns.org

### DDNS VARIABLES ###

# These variables are only necessary if you are using DDNS / comment them out if you don't use ddns
# Enter user id (use `id -u` to determine your user id)
# PUID=
# Enter group id (use `id -g` to determine your group id)
# PGID=
```

replace `ddclient.conf` might need to `sudo chown -R user:user  ddns` first

```
daemon=300
syslog=yes
verbose=yes
pid=/var/run/ddclient/ddclient.pid
ssl=yes
use=web

##
## Duckdns (http://www.duckdns.org/)
##
#

login=<sub-domain>
server=www.duckdns.org
password=<token>
protocol=duckdns
<sub-domain>.duckdns.org
```

**Comment by dadatuputi** [comment]
This looks like it would be useful for others in the future who want to use duck dns. Consider making a wiki entry for it for more visibility.

**Comment by casonadams** [comment]
@dadatuputi I don't see any `wiki` pages for this project.  Where can I post this so other can use the free duckdns service?

**Comment by casonadams** [comment]
I created one [here](https://github.com/casonadams/bitwarden_gcloud/wiki/DDNS-duckdns.org) but it would be nice to have a `wiki` in your repo.

**Comment by dadatuputi** [comment]
I had a wiki, but it was limited to collaborators only. I've opened it up to everyone on GitHub. Can you add a wiki page now?

**Comment by casonadams** [comment]
Yes added thanks!
