### ISSUE TITLE
error in proxy and bitwarden logs

### ISSUE THREAD

**Issue by kurti500** [dadatuputi/bitwarden_gcloud#42]
Hi,
any thoughts how this error in the proxy container logs can be avoided?

proxy           | {"level":"error","ts":1672992906.1859872,"logger":"http","msg":"looking up info for HTTP challenge","host":"xx.xxx.de","error":"no information found to solve challenge for identifier: xx.xxx.de"}

potentially related error in bitwarden container logs:

bitwarden       | [2023-01-06 09:10:18.098][_][WARN] Responding with registered (not_found) 404 catcher.
bitwarden       | [2023-01-06 09:15:06.381][_][WARN] Parameter guard `p: PathBuf` is forwarding: BadStart('.').
bitwarden       | [2023-01-06 09:15:06.381][_][ERROR] No matching routes for GET /.well-known/acme-challenge/RN_U0zFlBL_SiQnhQcqIR6aL0sAOXFnK6wU-M9ip0RA.
bitwarden       | [2023-01-06 09:15:06.381][_][WARN] Responding with registered (not_found) 404 catcher.
bitwarden       | [2023-01-06 13:04:53.934][request][INFO] GET /api/devices/knowndevice/myemail@xxx.de/73833eb1-5adb-44df-99d0-5b6705c9ad48

Thanks!

**Comment by dadatuputi** [comment]
Did you follow these steps? https://bradford.la/2020/self-host-bitwarden-on-google-cloud/#step-3-start-services-with-docker-compose

Looks like an ACME issue.

**Comment by kurti500** [comment]
> Did you follow these steps? https://bradford.la/2020/self-host-bitwarden-on-google-cloud/#step-3-start-services-with-docker-compose
> 
> Looks like an ACME issue.

yes, followed the guide for all steps, I am new to certs and ACME, any thoughts for debugging or topics I can check?
From a functional point of view (using vaultwarden in the browser as well as with the apps) I don't see any issues, but *something* seems not to be 100% right....

**Comment by dadatuputi** [comment]
I'm closing this now, but can re-open if it is obvious there's a bug. For now, it sounds like it's working fine, just the logs show that caddy is still trying to do ACME challenges? But when you access your vaultwarden web page it shows a valid LetsEncrypt cert?
