### ISSUE TITLE
Watchtower Logs Image Pull

### ISSUE THREAD

**Issue by crespire** [dadatuputi/bitwarden_gcloud#51]
Hi Bradford,

Thanks again for your work on this. I looked into my watchtower logs and saw this:

```
watchtower      | time="2023-01-26T12:49:53-05:00" level=info msg="Watchtower 1.5.1"
watchtower      | time="2023-01-26T12:49:53-05:00" level=info msg="Using no notifications"
watchtower      | time="2023-01-26T12:49:53-05:00" level=info msg="Checking all containers (except explicitly disabled with label)"
watchtower      | time="2023-01-26T12:49:53-05:00" level=info msg="Scheduling first run: 2023-01-29 03:00:00 -0500 EST"
watchtower      | time="2023-01-26T12:49:53-05:00" level=info msg="Note that the first check will be performed in 62 hours, 10 minutes, 6 seconds"
watchtower      | time="2023-01-29T03:00:09-05:00" level=warning msg="Could not do a head request for \"bitwarden_gcloud_proxy:latest\", falling back to regular pull." container=/proxy image="bitwarden_gcloud_proxy:latest"
watchtower      | time="2023-01-29T03:00:09-05:00" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:library/bitwarden_gcloud_proxy:pull\\\",error=\\\"insufficient_scope\\\"\"" container=/proxy image="bitwarden_gcloud_proxy:latest"
watchtower      | time="2023-01-29T03:00:10-05:00" level=info msg="Unable to update container \"/proxy\": Error response from daemon: pull access denied for bitwarden_gcloud_proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
watchtower      | time="2023-01-29T03:00:10-05:00" level=info msg="Session done" Failed=0 Scanned=6 Updated=0 notify=no
```

I wasn't able to find any reference to a `bitwarden_gcloud_proxy:latest` image anywhere in the `docker_compose.yml` either. Based on the information I can see, it seems like I can ignore this error? Can you confirm?

**Comment by dadatuputi** [comment]
Can you post your `docker-compose`? Unless you can confirm that it is the same as what's in the repo master?

**Comment by crespire** [comment]
> Can you post your `docker-compose`? Unless you can confirm that it is the same as what's in the repo master?

I am using the one on repo's master without changes.

**Comment by dadatuputi** [comment]
Ah yes, this is due to 837c1fceed76d156cdbdc71cc501d6c5790b94e3. I put in a temporary fix to suppress the warning, but long-term I will probably migrate some of the containers to separate docker images that publish to Docker hub and will have watchtower support. 

The discussion [here ](https://stackoverflow.com/questions/26423515/how-to-automatically-update-your-docker-containers-if-base-images-are-updated) indicates that the solution isn't straightforward, at least it isn't with the way this project is structured. 

I have this as an open request (#49) that I will get around to soon.
