### ISSUE TITLE
how to update a running instance?

### ISSUE THREAD

**Issue by kurti500** [dadatuputi/bitwarden_gcloud#60]
Not an issue at all, but I am wondering how to benefit from the enhancements and changes/improvements of this project on a running instance of it?
Just cloning the project again with git clone https://github.com/dadatuputi/bitwarden_gcloud.git plus updating .env and docker-compose.yml manually if required and doing another docker-compose up -d?
Will that work and be enough or is there more to be considered?
Thanks for your support and comments/advice.

**Comment by dadatuputi** [comment]
That's a good question, and probably deserves a wiki article at some point.

You should be able to simply pull the changes and update your copy of `.env`. If it has been some time, it might be worth copying `.env.template` again and migrating changes from your old `.env` to the new copy.

`docker-compose.yml` shouldn't have any customized parts, so no need to change anything in that file after you've pulled the latest changes.

I believe that will get you up to date. If you have issues, look at the docker logs and that will tell you a lot.
