### ISSUE TITLE
.env changes not affecting VW variables

### ISSUE THREAD

**Issue by kzaoaai** [dadatuputi/bitwarden_gcloud#63]
Changing domain or AUTH_TOKEN in the .env file did not have any effect. I had to use the config.json to be able to access to admin page and make changes.

**Comment by dadatuputi** [comment]
There is no `AUTH_TOKEN` in `.env.template`, do you mean `ADMIN_TOKEN`? Closing this as you're the only one with this issue, but will investigate if any others have this problem.
