### ISSUE TITLE
Log rotation?

### ISSUE THREAD

**Issue by crespire** [dadatuputi/bitwarden_gcloud#66]
Does the base vaultwarden image do log rotation? Or is there log rotation otherwise set up? I set it up on my fork of the old setup, and slowly trying to PR my changes into this new setup so I can get caught up with your latest changes.

**Comment by dadatuputi** [comment]
According to https://docs.docker.com/config/containers/logging/configure/ and running the command `docker info --format '{{.LoggingDriver}}'`, docker is using the `json-file` format. This format [appears to default to a single log file of unlimited size](https://docs.docker.com/config/containers/logging/json-file/#options), so it could indeed become a problem in the future. 

I am changing the docker-compose file to use log rotation, and pulling the persistent logs from the Caddyfile.
