### ISSUE TITLE
rclone failed to create config file

### ISSUE THREAD

**Issue by whyb0rn** [dadatuputi/bitwarden_gcloud#67]
By default, `rclone.conf` file is located in the `/data/rclone.conf` folder, `data` folder in  `backup` container is mounted as read-only, so rclone cannot create or modify the configuration file.
Solution: change the path to `rclone.conf` and give the folder where the configuration file is located write permissions.
Example: in `.env` change the line `BACKUP_RCLONE_CONF=/data/rclone.conf` to `BACKUP_RCLONE_CONF=/data/rclone/rclone.conf` and in `docker-compose.yml` add `- ${PWD}/bitwarden/rclone:/data/rclone` to `volumes:`

**Comment by dadatuputi** [comment]
That's not a bad solution, except I'm worried about those who have it in the old location getting a new docker-compose and not updating their .env and moving the file. 

I'd like a solution that keeps backwards compatibility, especially when it comes to backups, but not sure there is one without being excessively hacky. 

I did try to add a mount from ${PWD}/bitwarden/rclone.conf:/data/rclone/rclone.conf, however that fails to start when there is no rclone.conf in that location. 

In the meantime I'm going to update the bitwarden mount to not be read-only.

**Comment by dadatuputi** [comment]
I took another look at this, and came up with the changes as you suggested @whyb0rn- 

Changes: 
- `.env.template`: move to new location
  - `BACKUP_RCLONE_CONF=/data/rclone/rclone.conf`
- `docker-compose.yml`: make data read only, mount new `rclone` folder
  - ${PWD}/bitwarden:/data:ro
  - ${PWD}/bitwarden/rclone:/data/rclone
  - ${PWD}/bitwarden/backups:/data/backups

There are likely scenarios that I could imagine:
- New users - use new compose and new env template: OK
- Old users get the new compose - use new compose and old env: Probably OK
  - `rclone.conf` is still in `/data` which is READ ONLY. This will continue to work for backups until they update their rclone conf using the [instructions in the wiki](https://github.com/dadatuputi/bitwarden_gcloud/wiki/Backup#bitwarden-rclone-backups).
  - Resolution: Most old users won't have an issue. If they update their `rclone.conf` they will get a read-only error, and hopefully find the fix [in the wiki](https://github.com/dadatuputi/bitwarden_gcloud/wiki/Backup#troubleshooting-rclone-creation). 

I'm happy with this solution, and will be pushing the changes. Thanks @whyb0rn.
