### ISSUE TITLE
Can't get admin page enabled

### ISSUE THREAD

**Issue by rmeekers** [dadatuputi/bitwarden_gcloud#69]
I've set this in me `.env` file:

```
SIGNUPS_ALLOWED=false
ADMIN_TOKEN=***
```

But I keep getting this message on the /admin page: `The admin panel is disabled, please configure the 'ADMIN_TOKEN' variable to enable it`

(I've restarted the container after updating the `.env` file)

Any ideas?

**Comment by dadatuputi** [comment]
I just tested setting my `ADMIN_TOKEN` using the suggested `openssl rand -base64 48` command. It's possible that there is some base64 character that isn't playing nice with the env file / docker-compose. Try surrounding it in quotes, e.g. `ADMIN_TOKEN="/nSCL3cpzzmC983FFL9fSjgzBjcX0TmBHozhQj1zH5DTEAslXiJ/HIMfhigdRwI1"`. You might need to pull down the latest from the repo (`git pull`), as well as pull the latest docker images (`docker-compose pull`).

**Comment by rmeekers** [comment]
I've followed your instructions, but without luck.
The message remains.
