### ISSUE TITLE
Issue with SMTP_TLS in .env

### ISSUE THREAD

**Issue by doegluestick** [dadatuputi/bitwarden_gcloud#74]
When starting/stopping the container with docker-compose, I see this message:
`The SMTP_TLS variable is not set. Defaulting to a blank string.`

What is the use of SMTP_TLS and what should be its value if any?

**Comment by doegluestick** [comment]
* SMTP_TLS is commented out
* The rest of the SMTP settings are filled out
* I am able to get the fail2ban smtp to work without setting this variable
* I do have the latest files

I don't think this is a critical issue as smtp is working as intended with fail2ban.

**Comment by dadatuputi** [comment]
I've made some changes to the SMTP settings for fail2ban in 3373765b388576ddccbe6f5caf165967712db447. If your issue returns, try pulling the latest source and docker images and re-open.
