### ISSUE TITLE
Docker compose version

### ISSUE THREAD

**Issue by asardaes** [dadatuputi/bitwarden_gcloud#76]
Hello, I see that the setup is still using the `docker/compose` image to run `docker-compose` commands. This image has reached EOL and is already pretty old.

From what I can see, using a new version should be as easy as changing this line:

https://github.com/dadatuputi/bitwarden_gcloud/blob/552257c1190e8ad59157b5177bdfecce3441ac0f/utilities/install-alias.sh#L8

so that it says `docker compose` to use the (newer) docker image and its `compose` command.

Naturally, anyone with an existing setup would need to update the alias in `~/.bash_alias`

**Comment by dadatuputi** [comment]
Nice catch, updated. sed ommand to update `~/.bash_alias` will be in upcoming changelog
