### ISSUE TITLE
Newbie user need help for proxy/cloudflare/https 

### ISSUE THREAD

**Issue by id4vip** [dadatuputi/bitwarden_gcloud#8]
Hi,
Thanks for providing a this great arrangement. I just want to request you that please help us to make arrangement without the help of cloud flare. As for DDclient they are providing only if we have paid service or domain from them. Please elaborate your mechanism only with free available services like duckdns, lets encrypt etc.
 for free domains & cloudflare service i am geting this  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."

also one expert suggest me swag :-
https://docs.linuxserver.io/general/swag

**Comment by carceneaux** [comment]
ddclient is only used for Dynamic DNS. As I don't use CloudFlare as my DNS provider, I just removed ddclient from the `docker-compose.yml` and everything works great. _Note that without Dynamic DNS, you need to create the DNS A record yourself._

As it stands, the [ephemeral IP address](https://cloud.google.com/compute/docs/ip-addresses#ephemeraladdress) assigned to the Google Cloud VM Instance will persist as long as you don't power down the VM. As such, Dynamic DNS isn't required in my scenario.

**Comment by dadatuputi** [comment]
@id4vip - as @carceneaux says, ddns is optional. In [my extended blog post on the project](https://bradford.la/2020/self-host-bitwarden-on-google-cloud/), I write 

> Dynamic DNS is supported using ddclient through the ddclient docker container. The ddclient container provides a configuration file at ddns/ddclient.conf that you must edit to work with your particular DNS provider. Their GitHub repo here contains documentation on configuring ddclient and the ddclient.conf file.

> Note: ddclient.conf is placed in the ddns/ directory by the ddns container when it is run the first time, and any changes made to this configuration file will automatically be read in by the ddns container, no need to stop and start the container; you will see this shown in the logs.

If you would like to contribute a ddclient configuration, a wiki here might be a good place for that.
