### ISSUE TITLE
error proxy when start docker-compose up

### ISSUE THREAD

**Issue by vicjeremy** [dadatuputi/bitwarden_gcloud#84]
proxy         | {"level":"info","ts":1716442209.4840493,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15
proxy         | {"level":"info","ts":1716442210.8540995,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15
proxy         | {"level":"info","ts":1716442213.00745,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15
countryblock  | Added 5477 cn-aggregated.zone subnets to CN ipset
countryblock  | --2024-05-23 05:30:14--  https://www.ipdeny.com/ipblocks/data/aggregated/hk-aggregated.zone
countryblock  | Resolving www.ipdeny.com (www.ipdeny.com)... 51.15.12.186
countryblock  | Connecting to www.ipdeny.com (www.ipdeny.com)|51.15.12.186|:443... connected.
countryblock  | HTTP request sent, awaiting response... 304 Not Modified
countryblock  | File 'hk-aggregated.zone' not modified on server. Omitting download.
countryblock  | 
countryblock  | Downloaded zone file for HK
proxy         | {"level":"info","ts":1716442216.7592885,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15
countryblock  | Added 2683 hk-aggregated.zone subnets to HK ipset
countryblock  | --2024-05-23 05:30:17--  https://www.ipdeny.com/ipblocks/data/aggregated/au-aggregated.zone
countryblock  | Resolving www.ipdeny.com (www.ipdeny.com)... 51.15.12.186
countryblock  | Connecting to www.ipdeny.com (www.ipdeny.com)|51.15.12.186|:443... connected.
countryblock  | HTTP request sent, awaiting response... 304 Not Modified
countryblock  | File 'au-aggregated.zone' not modified on server. Omitting download.
countryblock  | 
countryblock  | Downloaded zone file for AU
proxy         | {"level":"info","ts":1716442223.6851983,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15
countryblock  | Added 5637 au-aggregated.zone subnets to AU ipset
countryblock  | /block.sh: waiting for SIGINT SIGTERM or SIGKILL to clean up
proxy         | {"level":"info","ts":1716442236.9056742,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15
proxy         | {"level":"info","ts":1716442262.9613702,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15
proxy         | {"level":"info","ts":1716442314.5999358,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
proxy         | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15

**Comment by dadatuputi** [comment]
Hello - looks like you have an error with your Caddyfile:

`proxy | Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': wrong argument count or unexpected line ending after 'tls', at /etc/caddy/Caddyfile:15`

If you're using the Caddyfile from the repo, you need to set your `.env` variables.

**Comment by vicjeremy** [comment]
im still confuse... i have already set my .env variables and im using duckdns.org, what else that i need to change?

**Comment by vicjeremy** [comment]
okay, i have been setting the proxy .env variables to my email but still stuck in here

proxy         | {"level":"error","ts":1716457609.313677,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"vault-vj.duckdns.org","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:connection - 202.80.214.226: Fetching http://vault-vj.duckdns.org/.well-known/acme-challenge/wK2BieepLtBS-X91euit8AUZyAIqe1gpXwmKCn9c1I0: Timeout during connect (likely firewall problem)"}
proxy         | {"level":"info","ts":1716457610.5490131,"logger":"tls.issuance.zerossl","msg":"generated EAB credentials","key_id":"UY8PG4enQ79LsygX8bGrnA"}
proxy         | {"level":"info","ts":1716457612.2108157,"logger":"tls.issuance.zerossl","msg":"waiting on internal rate limiter","identifiers":["vault-vj.duckdns.org"],"ca":"https://acme.zerossl.com/v2/DV90","account":"vjrmyp@gmail.com"}
proxy         | {"level":"info","ts":1716457612.210923,"logger":"tls.issuance.zerossl","msg":"done waiting on internal rate limiter","identifiers":["vault-vj.duckdns.org"],"ca":"https://acme.zerossl.com/v2/DV90","account":"vjrmyp@gmail.com"}
proxy         | {"level":"info","ts":1716457612.7836976,"logger":"tls.issuance.zerossl.acme_client","msg":"trying to solve challenge","identifier":"vault-vj.duckdns.org","challenge_type":"http-01","ca":"https://acme.zerossl.com/v2/DV90"}

**Comment by dadatuputi** [comment]
Are you following the instructions here: https://github.com/dadatuputi/bitwarden_gcloud/wiki/DDNS ?

Does your provided ddns resolve to your gcloud IP address right now? The WHOIS for the domain in your paste above does not show Google as the owner. Are you hosting this on gcloud? It will work on other providers, but the instructions will be different and you'll have to do some investigating on your own.
