### ISSUE TITLE
DDNS doesn't seem to run

### ISSUE THREAD

**Issue by fthobe** [dadatuputi/bitwarden_gcloud#85]
Hey,
thank you so much for your work. 
bitwarden made some steps forward regarding groups, any chance to update the repo?
Fab

**Comment by carceneaux** [comment]
This project already references the latest image for vaultwarden and watchtower keeps it up to date.

Please forgive me if I'm incorrect, but shouldn't this question be posed to [vaultwarden](https://github.com/dani-garcia/vaultwarden) instead of this project?

**Comment by fthobe** [comment]
Hey, you are right and I am wrong, I saw the bitwarden folder not updated for three years and misunderstood the nature of how you worked this project out entirely wrong. 

This is an amazing, I am deeply sorry and the god of ISO 27001 will praise you by the end of the year when I made this company pass the audit. 

XXX

**Comment by fthobe** [comment]
Hey @carceneaux , 

sorry for bothering you again on a saturday. 

So I went through the process and a lot of stuff is happening, but it seems to jump directly to let's encrypt without actually running, in fact the record is not created on cloudflare. 

In fact going through the process  NXDOMAIN looking up A for passwords.something.com fails

My  ~/bitwarden_gcloud/ddns/ddclient.conf file looks like this: 
```
use=web, web=checkip.dyndns.org/, web-skip='IP Address' # found after IP Address
protocol=cloudflare
zone=something.com
ttl=0
login=somebody@something.com
password=password
```

**Comment by dadatuputi** [comment]
This is really late, but did you work this out @fthobe? I assume it would be fixed by manually creating the record yourself on Cloudflare, as ddclient isn't used for creating records, just updating them. If you still have an issue, reopen this with an output of your ddclient logs using `docker-compose logs`.

**Comment by fthobe** [comment]
Hey, we can totally give this a try. Give me a couple of hours to have time and get back to you!
