### ISSUE TITLE
Port is already allocated on restart

### ISSUE THREAD

**Issue by mannyvergel** [dadatuputi/bitwarden_gcloud#9]
Bind for 0.0.0.0:443 failed: port is already allocated

Already tried docker-compose down and docker-compose up again to no avail. Any idea why this keeps on happening? Already happened twice.

**Comment by dadatuputi** [comment]
The two things I think this could be are 

1. The Caddy container is still running for some reason. Can you confirm with `docker ps -a` that you don't have any running containers after the `docker-compose down` command?
2. Sometimes a port will be 'reserved' for a time even after the process that used it has ended. Usually a wait of a few minutes will allow you to bind to that port again. 

Beyond that I'm not sure, you could try looking at netstat to see what process is listening on 443.

**Comment by carceneaux** [comment]
Confirmed this behavior. It appears to be an issue on the docker end...

![image](https://user-images.githubusercontent.com/17179966/113725870-c1d8d680-96c1-11eb-9734-1d405cb20b7b.png)

I was able to resolve this behavior with:

```bash
docker-compose down
sudo systemctl stop docker; sudo systemctl start docker
docker-compose up -d
```
